---

# The official package (http://packages.ubuntu.com/precise/collectd) is very out of date for 12.04 (4.10)
# This play builds from source as we need a current version that includes the write_graphite plugin.

- name: install collectd dependencies
  apt: >
    pkg=build-essential
    state=present

- name: download collectd
  get_url: >
    url=http://collectd.org/files/collectd-5.4.1.tar.bz2
    dest=/tmp/collectd.tar.bz2
    sha256sum=75452129f271cb0aad28e57f12a49070618bbb7b6a9d64cf869e8766fa2f66e0
  register: get_url
  sudo_user: "{{ common_service_user }}"

- name: unarchive collectd
  command: >
    tar jxf /tmp/collectd.tar.bz2 creates=/tmp/collectd-5.4.1
  when: get_url.changed

- name: move collectd source
  command: >
    mv /tmp/collectd-5.4.1 "{{ collectd_dir }}"
    creates="{{ collectd_dir }}"
  when: get_url.changed

- name: configure collectd
  shell: >
    ./configure
    chdir="{{ collectd_dir }}"
  when: get_url.changed

- name: build and install collectd
  shell: >
    make all install
    chdir="{{ collectd_dir }}"
  when: get_url.changed

- name: create /usr/sbin/collectd symlink
  file: >
    src="{{ collectd_dir }}/sbin/collectd"
    dest=/usr/sbin/collectd
    state=link

- name: adjust directory permissions
  file: >
    path="{{ collectd_dir }}"
    owner="{{ common_service_user }}"
    group="{{ common_service_user }}"
    state=directory
    recurse=yes
  when: get_url.changed

- name: setup collectd configuration
  template: >
    src=collectd.conf.j2
    dest="{{ collectd_dir }}/etc/collectd.conf"
    mode=0600
  sudo_user: "{{ common_service_user }}"
  notify: restart collectd

# TODO: Use supervisor

- name: install upstart script
  copy: >
    src=collectd.upstart.conf
    dest="/etc/init/collectd.conf"
    mode=0600
