---

- name: add node.js repository
  apt_repository: >
    repo="{{ nodejs_apt_repository }}"
    state=present

- name: install node.js
  apt: >
    pkg="{{ nodejs_apt_package }}"
    state=present
    update_cache=yes

- name: setup statsd directories
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ common_service_user }}"
    group="{{ common_service_user }}"
    mode=2775
  with_items:
    - "{{ statsd_app_dir }}"
    - "{{ statsd_log_dir }}"
    - "{{ statsd_cfg_dir }}"

- name: install statsd
  git: >
    dest="{{ statsd_app_dir }}"
    repo="{{ statsd_repos }}"
    version="{{ statsd_version }}"
    accept_hostkey=yes
  sudo_user: "{{ common_service_user }}"

- name: create statsd configuration
  template: >
    src=config.js.j2
    dest="{{ statsd_config_file }}"
    mode=0600
  sudo_user: "{{ common_service_user }}"
  notify: restart statsd

- name: create statsd supervisor configuration
  template: >
    src=statsd.supervisor.conf.j2
    dest="{{ supervisor_cfg_dir }}/statsd.conf"
    owner="{{ common_service_user }}"
    group="{{ common_service_user }}"
    mode=0644
  notify: restart supervisor

- name: install log rotation configurations
  template: >
    src=logrotate.j2
    dest="/etc/logrotate.d/statsd"
    owner=root
    group=root
    mode=0644
