---

- name: trust the rabbit repository
  apt_key: >
    url="{{ rabbitmq_apt_key }}"
    state=present

- name: add rabbitmq repository
  apt_repository: >
    repo="{{ rabbitmq_repository }}"
    state=present

- name: install rabbitmq
  apt: >
    pkg="{{ rabbitmq_pkg }}"
    state=present
    update_cache=yes

- name: create rabbitmq configuration directory
  file: >
    path="{{ rabbitmq_config_dir }}"
    owner=root group=root mode=0755
    state=directory

- name: install plugins
  rabbitmq_plugin: >
    names="{{ item }}"
    state=enabled
  with_items: rabbitmq_plugins
  notify: restart rabbitmq
