---

- name: trust the rabbit repository
  apt_key: >
    url="{{ rabbitmq_apt_key }}"
    state=present

- name: add rabbitmq repository
  apt_repository: >
    repo="{{ rabbitmq_repository }}"
    state=present

- name: install rabbitmq
  apt: >
    pkg="{{ rabbitmq_pkg }}"
    state=present
    update_cache=yes

- name: create rabbitmq configuration directory
  file: >
    path="{{ rabbitmq_config_dir }}"
    owner=root group=root mode=0755
    state=directory

- name: install plugins
  rabbitmq_plugin: >
    names="{{ item }}"
    state=enabled
  with_items: rabbitmq_plugins
  notify: restart rabbitmq

- name: create rabbitmq vhosts
  rabbitmq_vhost:
    name: "{{ item.vhost | default('/') }}"
    state: present
  with_items: rabbitmq_users
  when: rabbitmq_users | length > 0

- name: create rabbitmq users
  rabbitmq_user:
    user: "{{ item.name }}"
    password: "{{ item.pass }}"
    vhost: "{{ item.vhost | default('/') }}"
    configure_priv: "{{ item.configure_priv | default('.*') }}"
    read_priv: "{{ item.read_priv | default('.*') }}"
    write_priv: "{{ item.write_priv | default('.*') }}"
    tags: "{{ item.tags | default('') }}"
    state: present
  with_items: rabbitmq_users
  when: rabbitmq_users | length > 0
