---

- name: Provision the BUx external grader monitoring environment
  hosts: tag_role_monitor
  sudo: True

  vars_files:
    - "{{ secure_dir }}/{{ ec2_tag_environment }}/vars.yml"

  roles:
    - common
    - supervisor
    - graphite
    - statsd
