---

rabbitmq_apt_key: "http://www.rabbitmq.com/rabbitmq-signing-key-public.asc"
rabbitmq_repository: "deb http://www.rabbitmq.com/debian/ testing main"
rabbitmq_pkg: "rabbitmq-server"

rabbitmq_plugins:
  - rabbitmq_management

rabbitmq_config_dir: "/etc/rabbitmq"
